font_size 19
font_family PragmataPro Mono Liga Regular
#font_features PragmataProMonoLiga-Regular +cv03
adjust_line_height 1
disable_ligatures cursor
scrollback_lines 10000
cursor_blink_interval 1
enable_audio_bell no
# background #080808
shell_integration disabled
confirm_os_window_close 0
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url
show_hyperlink_targets no


# BEGIN_KITTY_THEME
# Tango Dark
include current-theme.conf
# END_KITTY_THEME
